version: '3.9'

services:
  ExperimentCourse11:
    image: transloadit/companion
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/app
      - /app/node_modules
      - /mnt/ExperimentCourse11-server-data:/mnt/ExperimentCourse11-server-data
    ports:
      - '3020:3020'
    command: '/app/src/standalone/start-server.js --config nodemon.json'
    env_file:
      - .env
